- name: Linux Requirements - User Creation
  hosts: centos
  tasks:
    - name: Create Linux User linuxTest
      become: true
      ansible.builtin.user:
        name: linuxTest
        shell: /bin/bash
        password: 
        state: present

- name: Linux Requirements - Yum Package
  hosts: centos
  tasks:
    - name: Install apache (yum)
      become: true
      ansible.builtin.yum:
        name: httpd
        state: present

- name: Linux Requirements - Apt Package
  hosts: ubuntu
  tasks:
    - name: Install apache (apt)
      become: true
      ansible.builtin.apt:
        name: apache2
        state: present
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
